---
# This playbook will install mysql and create db user and give permissions

- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
    - mysql-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql

- name: Start Mysql service
  service: name=mysqld state=started enabled=true

- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present 
              insertafter="^:OUTPUT" line="-I INPUT -p tcp --dport 3306 -j ACCEPT"
  notify:
    - restart iptables

