---


- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - php
    - php-mysql
    - git
    - libsemanage-python
    - libselinux-python

- name: insert iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:INPUT "
              line="-A INPUT -p tcp --dport {{ httpd_port }} -j ACCEPT"
  notify: restart iptables

- name: http service state
  service: name=httpd state=started enabled=yes

- name: Copy httpd config file
  template: src=httpd.conf dest=/etc/httpd/conf/
